package com.cts.eventsphere.dto.mapper.resource;

import com.cts.eventsphere.dto.resource.ResourceRequestDto;
import com.cts.eventsphere.model.Resource;
import com.cts.eventsphere.model.data.Availability;

/**
 * Mapper utility to convert ResourceRequestDto to Resource Entity.
 */
public class ResourceRequestDtoMapper {

    /**
     * Maps the incoming request DTO to the Resource JPA Entity.
     * Note: resourceId is not mapped here as it is auto-generated by UUID.
     */
    public static Resource toEntity(ResourceRequestDto dto) {
        if (dto == null) {
            return null;
        }

        Resource resource = new Resource();

        // Mapping fields from Record to Entity
        resource.setName(dto.name());
        resource.setUnit(dto.unit());
        resource.setVenueId(dto.venueId());
        resource.setType(dto.type());
        resource.setCostRate(dto.costRate());

        // Initializing defaults
        resource.setAvailability(Availability.available);

        // Note: 'name' from DTO isn't in your current Resource Entity.
        // If you add a 'name' field to the Resource class, map it here:
        // resource.setName(dto.name());

        return resource;
    }


}